### ISSUE TITLE
How can i use the same library in 2 acounts?

### ISSUE THREAD

**Issue by portacha** [awslabs/media-analysis-solution#15]
Can i share the same gallery with another user?

**Comment by dscpinheiro** [comment]
Hi @portacha,

Sorry for the delay in the response.

Could you clarify what you mean by sharing the gallery? If all you want is to give another user access to the solution, you should be able to add them in the Cognito user pool. Another option is to leverage [Elasticsearch backups](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html), since that's where all the results are stored.

**Comment by aassadza** [comment]
For your information: This Solutions Implementation has been superseded by [AWS Content Analysis](https://aws.amazon.com/solutions/implementations/aws-content-analysis/).
